# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-24 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passs',
        ),
    ]
