# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20191104_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(related_name='comments', to='post.Post'),
        ),
    ]
