# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20191104_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
