# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20191104_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
