# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20191105_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
