# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='static/images/'),
        ),
    ]
