# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20191105_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null='True', upload_to='static/profile/'),
        ),
    ]
