# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_auto_20191105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
