# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20191105_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='post/imageeee/3.jpeg', null='True', upload_to='static/profile/'),
        ),
    ]
