# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_post_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to=b'', verbose_name=post.models.Profile),
        ),
    ]
