# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='Image',
        ),
    ]
