# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:39
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_auto_20191115_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Image',
            field=models.ImageField(blank=True, null='True', upload_to=b'', verbose_name=django.contrib.auth.models.User),
        ),
    ]
