# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0043_auto_20191115_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Profile'),
        ),
    ]
