# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0044_auto_20191115_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Image',
        ),
    ]
