# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0045_remove_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/static/default/defaul.png', null='True', upload_to='static/profile/'),
        ),
    ]
